# Generated by Django 4.2.6 on 2023-10-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="category",
            field=models.ManyToManyField(to="main.category"),
        ),
    ]
