# Generated by Django 4.2.6 on 2023-10-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_subscribe"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrendingGames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game", models.ManyToManyField(related_name="trgame", to="main.game")),
            ],
            options={
                "verbose_name": "TrendingGame",
                "verbose_name_plural": "TrendingGames",
            },
        ),
    ]
