# Generated by Django 4.2.6 on 2023-10-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_trendinggames_game"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularGames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("popular_game", models.ManyToManyField(to="main.game")),
            ],
            options={
                "verbose_name": "PopularGame",
                "verbose_name_plural": "PopularGames",
            },
        ),
    ]
