# Generated by Django 4.2.6 on 2023-10-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_populargames"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game", models.ManyToManyField(to="main.game")),
            ],
            options={
                "verbose_name": "TopCategory",
                "verbose_name_plural": "TopCategories",
            },
        ),
    ]
