# Generated by Django 4.2.6 on 2023-10-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_topcategories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                verbose_name="Price Discount",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, verbose_name="Game Price"
            ),
        ),
    ]
