# Generated by Django 4.2.6 on 2023-10-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_game_discount_alter_game_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="topcategories",
            name="category",
            field=models.ManyToManyField(to="main.category"),
        ),
    ]
