# Generated by Django 4.2.6 on 2023-10-18 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_remove_topcategories_category_topcategories_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topcategories",
            name="category",
        ),
    ]
