# Generated by Django 4.2.6 on 2023-10-20 14:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_remove_topcategories_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=254, verbose_name="Contact title"),
                ),
                ("subtitle", models.CharField(max_length=254, verbose_name="Subtitle")),
                ("text", models.TextField(verbose_name="Contact text")),
                ("address", models.CharField(max_length=50, verbose_name="Address")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("email", models.EmailField(max_length=50, verbose_name="Email")),
            ],
            options={
                "verbose_name": "ContactUs",
                "verbose_name_plural": "ContactUs",
            },
        ),
    ]
