# Generated by Django 4.2.6 on 2023-10-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_contactus"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUsF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("surname", models.CharField(max_length=50, verbose_name="Surname")),
                ("email", models.EmailField(max_length=50, verbose_name="Email")),
                ("subject", models.CharField(max_length=50, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
            ],
            options={
                "verbose_name": "ContactUsF",
                "verbose_name_plural": "ContactUsF",
            },
        ),
    ]
