# Generated by Django 4.2.6 on 2023-10-20 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_contactusf"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactusf",
            options={
                "verbose_name": "ContactUs Form",
                "verbose_name_plural": "ContactUs Form",
            },
        ),
    ]
